<?php
// ============================================
// SHARED PRODUCT DATA - parts/products_data.php
// Single source of truth for all product info
// ============================================

$products = [
  1 => [
    "name"  => "Fiddle Leaf Fig",
    "latin" => "Ficus lyrata",
    "price" => 89,
    "image" => "../images/fiddle-leaf-fig.jpg",
    "desc"  => "A striking statement plant with large, violin-shaped leaves. Perfect for bright, indirect light and adding dramatic height to any space.",
    "light" => "Bright Indirect",
    "water" => "Weekly",
    "care"  => "Moderate",
  ],
  2 => [
    "name"  => "Monstera Deliciosa",
    "latin" => "Monstera deliciosa",
    "price" => 65,
    "image" => "../images/monstera.jpg",
    "desc"  => "The iconic Swiss cheese plant with stunning split leaves. A tropical beauty that thrives in bright, indirect light.",
    "light" => "Bright Indirect",
    "water" => "Weekly",
    "care"  => "Easy",
  ],
  3 => [
    "name"  => "Snake Plant",
    "latin" => "Sansevieria trifasciata",
    "price" => 45,
    "image" => "../images/snake-plant.jpg",
    "desc"  => "One of the most resilient houseplants. Its upright, sword-like leaves make it a modern architectural accent for any room.",
    "light" => "Low to Bright",
    "water" => "Bi-weekly",
    "care"  => "Easy",
  ],
  4 => [
    "name"  => "Golden Pothos",
    "latin" => "Epipremnum aureum",
    "price" => 32,
    "image" => "../images/pothos.jpg",
    "desc"  => "A cascading vine with heart-shaped golden-green leaves. Nearly indestructible and perfect for shelves and hanging planters.",
    "light" => "Low to Bright",
    "water" => "Weekly",
    "care"  => "Easy",
  ],
  5 => [
    "name"  => "Peace Lily",
    "latin" => "Spathiphyllum wallisii",
    "price" => 48,
    "image" => "../images/peace-lily.jpg",
    "desc"  => "An elegant flowering plant with glossy dark leaves and graceful white blooms. Thrives in low light and purifies the air naturally.",
    "light" => "Low to Medium",
    "water" => "Weekly",
    "care"  => "Easy",
  ],
  6 => [
    "name"  => "Bird of Paradise",
    "latin" => "Strelitzia reginae",
    "price" => 110,
    "image" => "../images/bird-of-paradise.jpg",
    "desc"  => "A tropical showstopper with large, banana-like leaves that bring instant resort vibes to any interior.",
    "light" => "Bright Direct",
    "water" => "Weekly",
    "care"  => "Moderate",
  ],
  7 => [
    "name"  => "Jade Plant",
    "latin" => "Crassula ovata",
    "price" => 28,
    "image" => "../images/jade-plant.jpg",
    "desc"  => "A classic succulent with thick, glossy oval leaves on woody stems. Known as a symbol of good luck and prosperity.",
    "light" => "Bright Direct",
    "water" => "Bi-weekly",
    "care"  => "Easy",
    "light" => "Bright Indirect",
    "water" => "Bi-weekly",
    "care"  => "Moderate",
  ],
  8 => [
    "name"  => "ZZ Plant",
    "latin" => "Zamioculcas zamiifolia",
    "price" => 52,
    "image" => "../images/zz-plant.jpg",
    "desc"  => "A virtually indestructible plant with glossy, dark green waxy leaves. Thrives on neglect and tolerates low-light conditions.",
    "light" => "Low to Bright",
    "water" => "Bi-weekly",
    "care"  => "Easy",
  ],
  9 => [
    "name"  => "Alocasia Polly",
    "latin" => "Alocasia amazonica",
    "price" => 72,
    "image" => "../images/alocasia.jpg",
    "desc"  => "Known as the African Mask Plant, its dramatic arrow-shaped leaves with bold white veins make it a collector's favorite.",
    "light" => "Bright Indirect",
    "water" => "Weekly",
    "care"  => "Advanced",
  ],
  10 => [
    "name"  => "Calathea Orbifolia",
    "latin" => "Goeppertia orbifolia",
    "price" => 58,
    "image" => "../images/calathea.jpg",
    "desc"  => "A prayer plant with large, round leaves adorned with silvery-green stripes. Its leaves gently fold upward at night.",
    "light" => "Medium Indirect",
    "water" => "Weekly",
    "care"  => "Moderate",
  ],
  11 => [
    "name"  => "Pink Princess Philodendron",
    "latin" => "Philodendron erubescens",
    "price" => 145,
    "image" => "../images/philodendron.jpg",
    "desc"  => "A rare and highly sought-after plant with stunning dark green and bubblegum-pink variegated leaves. A true collector's gem.",
    "light" => "Bright Indirect",
    "water" => "Weekly",
    "care"  => "Moderate",
  ],
  12 => [
    "name"  => "Rubber Plant",
    "latin" => "Ficus elastica",
    "price" => 55,
    "image" => "../images/rubber-plant.jpg",
    "desc"  => "A bold statement plant with thick, glossy burgundy leaves. Easy to care for and grows into an impressive indoor tree.",
    "light" => "Medium to Bright",
    "water" => "Weekly",
    "care"  => "Easy",
  ],
  13 => [
    "name"  => "Ceramic Planter",
    "latin" => "Handcrafted Stoneware",
    "price" => 45,
    "image" => "../images/hero-plants.jpg",
    "desc"  => "A handcrafted ceramic planter designed to complement any of our plants. Available in four signature colorways.",
    "light" => "—",
    "water" => "—",
    "care"  => "—",
  ],
];
